name: GitHub App Installation Token Action
description: A GitHub Action that can be used to generate scoped credentials for use within your workflow using an App integration.
runs:
  using: 'node20'
  main: 'dist/index.mjs'
inputs:
  app_id:
    required: true
    description: The app identifier
  private_key:
    required: true
    description: The private key of the application
  installation_id:
    required: true
    description: The installation identifier
  permissions:
    required: true
    default: default
    description: |
      The permissions to be granted to the access token. There are two supported values:

      - `default` - Uses the default permissions assigned to the App
      - A JSON string (i.e `{"contents": "write"}`) - Specific permissions required by your workflow
        - Note: The app installation must have already been granted these permissions.
        - Accepted values can be found here: https://docs.github.com/en/rest/apps/apps#create-an-installation-access-token-for-an-app
outputs:
  token:
    description: The generated access token that can be passed into other actions or used with in Git operations.
  permissions:
    description: A JSON string containing the permissions granted to the access token.
