name: App Access Token Action
description: Mints app specific access tokens for used with the GitHub API
runs:
  using: 'node16'
  main: 'dist/index.js'
inputs:
  app_id:
    description: The app identifier
    required: true
  installation_id:
    description: The installation identifier
    required: true
  private_key:
    description: The private key of the application
    required: true
outputs:
  token:
    description: The minted access token
