name: Test
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test-with-explicit-permissions:
    name: Test (with explicit permissions)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action
        uses: actions/checkout@v3

      - name: Run Action
        uses: ./
        id: github-auth
        with:
          app_id: ${{ secrets.GH_AUTH_APP_ID }}
          private_key: ${{ secrets.GH_AUTH_PRIVATE_KEY }}
          installation_id: ${{ secrets.GH_AUTH_INSTALLATION_ID }}
          permissions: '{"contents": "read"}'

      - name: Test Auth
        uses: actions/checkout@v3
        with:
          token: ${{ steps.github-auth.outputs.token }}

  test-with-default-permissions:
    name: Test (with default permissions)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action
        uses: actions/checkout@v3

      - name: Run Action
        uses: ./
        id: github-auth
        with:
          app_id: ${{ secrets.GH_AUTH_APP_ID }}
          private_key: ${{ secrets.GH_AUTH_PRIVATE_KEY }}
          installation_id: ${{ secrets.GH_AUTH_INSTALLATION_ID }}
          permissions: default

      - name: Test Auth
        uses: actions/checkout@v3
        with:
          token: ${{ steps.github-auth.outputs.token }}
